OSSM-1932: post-submit: Fix the creation of fake extensions
They should be created *after* envoy is built otherwise the bazel-bin
directory that's created will not be a symlink to bazel internal
directoris, thus the post-submit job will fail with

```
gsutil cp bazel-bin/src/envoy/envoy_tar.tar.gz gs://maistra-prow-testing/proxy/envoy-alpha-3909d6cc99752588ae238b32887880e70c97be19.tar.gz
CommandException: No URLs matched: bazel-bin/src/envoy/envoy_tar.tar.gz
```