Include missing headers (#3920)
Some combinations of compiler/c++ libraries don't include <optional>
header by default, making the build fail with

```
./extensions/common/wasm/json_util.h:36:6: error: no template named 'optional' in namespace 'std'
```